from firmware_sources import runtime_source
import re
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'tools'))
import profiles  # noqa: E402
sys.path.insert(0, str(ROOT / 'screen_manager/app'))
sys.path.insert(0, str(ROOT / 'tests'))
import test_portal
import tile_icons
from core import discover, packets, state_message, validate_layout

HEADER = runtime_source()

class IconSetTests(unittest.TestCase):
    def test_set_is_complete_and_carried_by_every_icon_font(self):
        self.assertEqual(len(tile_icons.ICONS), 151)
        self.assertTrue(any(group == 'Media and music' and len(icons) >= 20 for group, icons in tile_icons.GROUPS))
        self.assertEqual(len(set(tile_icons.GLYPHS.values())), len(tile_icons.GLYPHS))
        for code in tile_icons.GLYPHS.values():
            self.assertRegex(code, r'^F[0-9A-F]{4}$')
        wanted = [f'\\U000{code}' for code in tile_icons.GLYPHS.values()]
        for name in ('checkout/cyd.yaml', 'checkout/guition.yaml', 'packages/cyd.yaml', 'packages/guition.yaml'):
            text = profiles.resolved(name)
            fonts = re.findall(r'materialdesignicons-webfont\.ttf["\']\n    id: (\w+)\n    size: \d+\n    bpp: 4\n    glyphs: (.*)\n', text)
            # Back's font carries the chevron and nothing else, written out by hand in the shared core; every other icon
            # font carries the whole set. The home key is the Tessera mark (firmware 0.10.0+), a picture, not a glyph.
            self.assertEqual([font for font, _ in fonts], ['materialdesign_icons', 'materialdesign_icons_mini',
                                                           'materialdesign_icons_back', 'materialdesign_icons_status',
                                                           'materialdesign_icons_big', 'watch_icon'], name)
            self.assertEqual(dict(fonts)['materialdesign_icons_back'].strip(), '["\\U000F0141"]', name)
            # The top bar's Wi-Fi bars (firmware 0.38.0): struck through, then one to four bars, the order header_bar.h counts;
            # then the battery's icons the tile icons lack (firmware 0.41.0, battery_status.h): charging per ten up to 90,
            # the charging outline and the alert outline.
            status = re.search(r'id: materialdesign_icons_status\n    size: \d+\n    bpp: 4\n    glyphs: (\[.*?\])', text, re.S)[1]
            self.assertEqual(re.findall(r'\\U000(F[0-9A-F]{4})', status),
                             ['F092E', 'F091F', 'F0922', 'F0925', 'F0928', 'F089C', 'F0086', 'F0087', 'F0088', 'F089D', 'F0089',
                              'F089E', 'F008A', 'F008B', 'F089F', 'F10CD'], name)
            # The battery's level icons, battery-unknown and the full charging one are tile icons already.
            for code in ('F0079', 'F007A', 'F007B', 'F007C', 'F007D', 'F007E', 'F007F', 'F0080', 'F0081', 'F0082', 'F0091', 'F0084'):
                self.assertIn(code, tile_icons.GLYPHS.values(), code)
            self.assertTrue(fonts[0][1].startswith('&tile_icons ')
                            and all(g == '*tile_icons' for font, g in fonts[1:]
                                    if font not in ('materialdesign_icons_big', 'materialdesign_icons_back', 'materialdesign_icons_status')), name)
            block = text.split('glyphs: &tile_icons ', 1)[1].split('\n\n', 1)[0]
            self.assertEqual(re.findall(r'- "(\\U000F[0-9A-F]{4})"', block), wanted, name)
            # The big font of the full-page card (firmware 0.2.62+) carries the subset the screen draws on its own.
            self.assertEqual(dict(fonts)['materialdesign_icons_big'].split('  #')[0].strip(), '&tile_icons_big', name)
            big = text.split('glyphs: &tile_icons_big', 1)[1].split('\n\n', 1)[0]
            self.assertEqual(re.findall(r'- "(\\U000F[0-9A-F]{4})"', big), [f'\\U000{tile_icons.GLYPHS[n]}' for n in tile_icons.BIG_GLYPHS], name)
            self.assertNotIn('MDI_GLYPH', text, name)
        self.assertTrue((ROOT / 'web/src/assets/tile-icons.woff').exists())

    def test_firmware_name_table_mirrors_the_set(self):
        header = (ROOT / 'components/smart_display/tile_icon_names.h').read_text()
        self.assertIn('GENERATED by tools/generate_icons.py', header)
        entries = re.findall(r'^  \{"([a-z0-9-]+)", 0x(F[0-9A-F]{4})\},$', header, re.M)
        self.assertEqual(dict(entries), tile_icons.GLYPHS)
        self.assertEqual(len(entries), len(tile_icons.GLYPHS))

    def test_every_glyph_the_firmware_draws_is_in_the_set(self):
        sources = [HEADER] + [profiles.text(name).split('glyphs: &tile_icons', 1)[0] for name in ('checkout/cyd.yaml', 'checkout/guition.yaml')]
        used = {code.upper() for source in sources for code in re.findall(r'\\U000(F[0-9A-Fa-f]{4})', source)}
        self.assertLessEqual(used, set(tile_icons.GLYPHS.values()))

    def test_editor_predictions_mirror_the_firmware(self):
        body = HEADER.split('inline const char *icon_for(const Tile &tile) {', 1)[1].split('\n}', 1)[0]
        native = {}
        for domains, code in re.findall(r'if \((d == "\w+"(?: \|\| d == "\w+")*)\) return "\\U000(F[0-9A-F]{4})";', body):
            for domain in re.findall(r'"(\w+)"', domains):
                native[domain] = code
        # The built-in cards pick per entity, not per domain: a clock, the settings page, a page to go to, the map or the
        # energy card (whose icon is the editor's alone: the card draws its diagram, so it is not in the big icon font).
        settings, page, map_tile, energy, clock = re.search(
            r'if \(d == "screen"\) return tile\.is_settings\(\) \? "\\U000(F[0-9A-F]{4})" : tile\.is_page\(\) \? "\\U000(F[0-9A-F]{4})" : tile\.entity == "screen\.map" \? "\\U000(F[0-9A-F]{4})" : tile\.is_energy\(\) \? "\\U000(F[0-9A-F]{4})" : "\\U000(F[0-9A-F]{4})";', body).groups()
        builtin = {entity: tile_icons.GLYPHS[name] for entity, name in tile_icons.BUILTIN_TILES.items()}
        self.assertEqual({'screen.settings': settings, 'screen.clock': clock, 'screen.map': map_tile, **{f'screen.page_{n}': page for n in range(1, 9)}}, builtin)
        self.assertEqual({'screen.energy': energy}, {entity: tile_icons.GLYPHS[name] for entity, name in tile_icons.DIAGRAM_TILES.items()})
        self.assertEqual(tile_icons.editor()['builtin'], {**builtin, 'screen.energy': energy})
        self.assertEqual(tile_icons.GLYPHS[tile_icons.DEFAULTS['screen']], clock)
        expected = {domain: tile_icons.GLYPHS[name] for domain, name in tile_icons.DEFAULTS.items() if domain != 'screen'}
        self.assertEqual(native, expected)
        self.assertIn(f'return "\\U000{tile_icons.GLYPHS[tile_icons.FALLBACK]}";', body)
        weather = HEADER.split('inline const char *weather_icon(const std::string &condition) {', 1)[1].split('\n}', 1)[0]
        for state, name in tile_icons.WEATHER.items():
            self.assertRegex(weather, rf'condition == "{re.escape(state)}"[^\n]*return "\\U000{tile_icons.GLYPHS[name]}";')
        editor = tile_icons.editor()
        self.assertEqual(sum(len(group['icons']) for group in editor['groups']), 151)
        self.assertIn(f'"\\U000{editor["sun"]["above_horizon"]}" : "\\U000{editor["sun"]["below_horizon"]}"', HEADER)

class IconOptionTests(unittest.IsolatedAsyncioTestCase):
    def test_validation_accepts_the_set_and_auto_only(self):
        for value in ('auto', 'lamp', 'spotify', 'speaker'):
            layout = validate_layout({'title': 'Home', 'tiles': [{'entity': 'media_player.a', 'options': {'icon': value}}]})
            self.assertEqual(layout['tiles'][0]['options']['icon'], value)
        for value in ('mdi:lamp', 'F06B5', 'weather-fog', 'unknown', '', None, 42, ['lamp']):
            with self.assertRaises(ValueError):
                validate_layout({'title': 'Home', 'tiles': [{'entity': 'light.a', 'options': {'icon': value}}]})

    def test_wire_carries_the_codepoint_chosen_or_from_home_assistant(self):
        states = {'light.a': {'state': 'on', 'attributes': {'icon': 'mdi:floor-lamp'}},
                  'light.b': {'state': 'on', 'attributes': {'icon': 'mdi:not-in-the-set'}},
                  'light.c': {'state': 'on', 'attributes': {}}}
        chosen = state_message(0, {'entity': 'light.a', 'name': '', 'options': {'icon': 'lamp', 'tap': 'toggle'}}, states)
        self.assertEqual(chosen['o'], {'tap': 'toggle', 'icon': 'F06B5'})
        automatic = state_message(0, {'entity': 'light.a', 'name': '', 'options': {'icon': 'auto'}}, states)
        self.assertEqual(automatic['o'], {'icon': 'F08DD'})
        self.assertEqual(state_message(0, {'entity': 'light.a', 'name': ''}, states)['o'], {'icon': 'F08DD'})
        self.assertNotIn('o', state_message(0, {'entity': 'light.b', 'name': ''}, states))
        self.assertNotIn('o', state_message(0, {'entity': 'light.c', 'name': ''}, states))
        self.assertEqual(state_message(0, {'entity': 'light.c', 'name': '', 'options': {'icon': 'auto'}}, states)['o'], {})
        packets(chosen)

    def test_discovery_reports_home_assistant_icons_the_screen_can_draw(self):
        states = {'light.a': {'state': 'on', 'attributes': {'icon': 'mdi:chandelier'}}, 'light.b': {'state': 'off', 'attributes': {'icon': 'hass:x'}}}
        _, entities = discover([{'entity_id': 'light.a'}], states, [], [])
        self.assertEqual({e['id']: e['icon'] for e in entities}, {'light.a': 'F1793', 'light.b': None})

    async def test_old_editor_preserves_icon_and_explicit_auto_clears(self):
        with tempfile.TemporaryDirectory() as tmp:
            m = test_portal.ManagerTests().setup_manager(Path(tmp) / 'screens.json')
            m.save('text.screen', {'title': 'Home', 'tiles': [{'entity': 'light.a', 'options': {'icon': 'spotify'}}]})
            m.save('text.screen', {'title': 'Home', 'tiles': [{'entity': 'light.a', 'options': {'inline': 'none'}}]})
            self.assertEqual(m.layouts['text.screen']['tiles'][0]['options'], {'inline': 'none', 'icon': 'spotify'})
            await m.sync_one('text.screen', m.layouts['text.screen'])
            self.assertEqual(m.ha.messages[1][1]['o']['icon'], 'F04C7')
            m.save('text.screen', {'title': 'Home', 'tiles': [{'entity': 'light.a', 'options': {'icon': 'auto'}}]})
            self.assertEqual(m.layouts['text.screen']['tiles'][0]['options']['icon'], 'auto')

if __name__ == '__main__':
    unittest.main()
